// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class SharedController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _alerts = "_alerts";
                public readonly string _BootstrapLayout_basic = "_BootstrapLayout.basic";
                public readonly string _BootstrapLayout_empty = "_BootstrapLayout.empty";
                public readonly string _BootstrapLayout_narrow = "_BootstrapLayout.narrow";
                public readonly string _html5shiv = "_html5shiv";
                public readonly string _Layout = "_Layout";
                public readonly string _LoginPartial = "_LoginPartial";
                public readonly string _validationSummary = "_validationSummary";
                public readonly string Create = "Create";
                public readonly string Details = "Details";
                public readonly string Error = "Error";
                public readonly string Index = "Index";
            }
            public readonly string _alerts = "~/Views/Shared/_alerts.cshtml";
            public readonly string _BootstrapLayout_basic = "~/Views/Shared/_BootstrapLayout.basic.cshtml";
            public readonly string _BootstrapLayout_empty = "~/Views/Shared/_BootstrapLayout.empty.cshtml";
            public readonly string _BootstrapLayout_narrow = "~/Views/Shared/_BootstrapLayout.narrow.cshtml";
            public readonly string _html5shiv = "~/Views/Shared/_html5shiv.cshtml";
            public readonly string _Layout = "~/Views/Shared/_Layout.cshtml";
            public readonly string _LoginPartial = "~/Views/Shared/_LoginPartial.cshtml";
            public readonly string _validationSummary = "~/Views/Shared/_validationSummary.cshtml";
            public readonly string Create = "~/Views/Shared/Create.cshtml";
            public readonly string Details = "~/Views/Shared/Details.cshtml";
            public readonly string Error = "~/Views/Shared/Error.cshtml";
            public readonly string Index = "~/Views/Shared/Index.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
